// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIU_keoLvYbCZvCm7R9Y0rR6WwwYC-DcA',
    appId: '1:596330969866:web:ee8036f3fa95840b13d8f3',
    messagingSenderId: '596330969866',
    projectId: 'broj-bodova',
    authDomain: 'broj-bodova.firebaseapp.com',
    storageBucket: 'broj-bodova.appspot.com',
    measurementId: 'G-DE20RHYZD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf6ZGhCyjJ0Dh35yfnH2UokZ6-fMm7m4w',
    appId: '1:596330969866:android:8721c792f84f866213d8f3',
    messagingSenderId: '596330969866',
    projectId: 'broj-bodova',
    storageBucket: 'broj-bodova.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_9Eag4kVT3Uc9M3yePxFzO5W6OQQ3iwE',
    appId: '1:596330969866:ios:fad2af6ec3f530d913d8f3',
    messagingSenderId: '596330969866',
    projectId: 'broj-bodova',
    storageBucket: 'broj-bodova.appspot.com',
    iosClientId: '596330969866-tp1jt16gtq6ksvvak1u2pve4ftt20gue.apps.googleusercontent.com',
    iosBundleId: 'com.example.kolkoJeZaPet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_9Eag4kVT3Uc9M3yePxFzO5W6OQQ3iwE',
    appId: '1:596330969866:ios:fad2af6ec3f530d913d8f3',
    messagingSenderId: '596330969866',
    projectId: 'broj-bodova',
    storageBucket: 'broj-bodova.appspot.com',
    iosClientId: '596330969866-tp1jt16gtq6ksvvak1u2pve4ftt20gue.apps.googleusercontent.com',
    iosBundleId: 'com.example.kolkoJeZaPet',
  );
}
